console.log('teeste')

{ 
   {
     {
        {
            {
                {
                    {
                        {
                            {
                                {
                                    {
                                        {
                                            {
                                                {
                                                    console.log('Olá')
                                                    console.log('Mundo')
                                                }
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
     }
   }  
}